### PR TITLE
all configurable PKGX_DIST_URL

### LINKED ISSUE #71: pkgx distribution host endpoint override
Would be great if the distribution host endpoint `https://dist.pkgx.dev` can be override with `env` value. This would allow users behind corp firewall to reroute it via middleware such as gateway or Artifactory.

e.g.
export XDG_DIST_URI=https://corp-endpoint/pkgx

### PR DESCRIPTION
**Pull request by jhheider**
closes #71

### CODE REVIEW

**Comment by jhheider** [comment]
i don't see where this change would have made unicode's package.yml unparseable... @mxcl does this look like some other regression to you?

**Comment by mxcl** [comment]
Yeah cannot be due to this change. But what can it be? deno varies yes, but the deno std lib that parses yaml is pinned.

**Comment by mxcl** [comment]
Running CI on `main` https://github.com/pkgxdev/libpkgx/actions/runs/9037714306

**Comment by jhheider** [comment]
> Running CI on `main` https://github.com/pkgxdev/libpkgx/actions/runs/9037714306

well, the failure is some kind of relief, certainly.

**Comment by jhheider** [comment]
i was thinking the problem could have unicode characters and linux charsets; but hexedit scanning of that file doesn't support it, and most of the rest of our stack should complain if that were it.

**Pull request merged**
