### PR TITLE
Fix slow pantry caching by using memory as much as possible

### PR DESCRIPTION
**Pull request by felipecrs**
Thanks to @amospalla's [hint](https://github.com/pkgxdev/pkgx/issues/1022#issuecomment-2366257827).

- Closes https://github.com/pkgxdev/pkgx/issues/1022

### CODE REVIEW

**Comment by felipecrs** [comment]
Before:

```console
> rm -rf ~/.cache/pkgx ~/.local/share/pkgx ~/.pkgx
> time deno task run --sync
Task run deno run --unstable-fs --unstable-ffi -A ./entrypoint.ts "--sync"

deno task run --sync  1.67s user 2.52s system 7% cpu 56.122 total
```

After:

```console
> rm -rf ~/.cache/pkgx ~/.local/share/pkgx ~/.pkgx
> time deno task run --sync
Task run deno run --unstable-fs --unstable-ffi -A ./entrypoint.ts "--sync"

deno task run --sync  1.22s user 0.90s system 77% cpu 2.759 total
```

**Comment by felipecrs** [comment]
Before:

```console
> rm -rf ~/.cache/pkgx ~/.local/share/pkgx ~/.pkgx
> time deno task run --sync
Task run deno run --unstable-fs --unstable-ffi -A ./entrypoint.ts "--sync"

deno task run --sync  1.67s user 2.52s system 7% cpu 56.122 total
```

After:

```console
> rm -rf ~/.cache/pkgx ~/.local/share/pkgx ~/.pkgx
> time deno task run --sync
Task run deno run --unstable-fs --unstable-ffi -A ./entrypoint.ts "--sync"

deno task run --sync  1.22s user 0.90s system 77% cpu 2.759 total```

**Comment by felipecrs** [comment]
@mxcl, CI failure is not related.

**Comment by mxcl** [comment]
Amazing!

**Comment by jhheider** [comment]
👏

**Pull request merged**
